/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zaka_rplmart;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nindra
 */
public class frmKaryawan extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmKaryawan
     */
    config configurasi = new config();
    DefaultTableModel model = new DefaultTableModel();
    
    public frmKaryawan() {
        initComponents();
        configurasi.koneksi();
        atur_tabel();
        aksi_simpan();      
        muat_tabel();
        
        //rata tengah
        Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = ( posisi.width - this.getWidth() ) / 2;
        int y = ( posisi.height - this.getHeight() ) /2;
        this.setLocation(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        btn_simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_ubah = new javax.swing.JButton();
        txt_kode = new javax.swing.JTextField();
        btn_hapus = new javax.swing.JButton();
        txt_nama = new javax.swing.JTextField();
        btn_batal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        radio_laki = new javax.swing.JRadioButton();
        radio_perempuan = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        radio_admin = new javax.swing.JRadioButton();
        radio_kasir = new javax.swing.JRadioButton();
        btn_keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_simpan.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setBackground(new java.awt.Color(234, 62, 62));
        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA PETUGAS");
        jLabel1.setOpaque(true);

        jLabel2.setText("Kode Petugas");

        btn_ubah.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btn_ubah.setText("Ubah");
        btn_ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ubahMouseClicked(evt);
            }
        });
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        txt_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodeActionPerformed(evt);
            }
        });

        btn_hapus.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        btn_batal.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Petugas");

        jLabel6.setBackground(new java.awt.Color(46, 46, 46));
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Klik tabel untuk mengedit data");
        jLabel6.setOpaque(true);

        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });

        jLabel4.setText("User");

        jLabel5.setText("Jenis Kelamin");

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        jLabel7.setText("Password");

        buttonGroup1.add(radio_laki);
        radio_laki.setText("Laki - Laki");

        buttonGroup1.add(radio_perempuan);
        radio_perempuan.setText("Perempuan");

        jLabel8.setText("Level");

        buttonGroup2.add(radio_admin);
        radio_admin.setText("Admin");
        radio_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_adminActionPerformed(evt);
            }
        });

        buttonGroup2.add(radio_kasir);
        radio_kasir.setText("Kasir");

        btn_keluar.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(radio_laki)
                            .addComponent(radio_perempuan)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_admin)
                            .addComponent(radio_kasir)
                            .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_kode))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ubah)
                            .addComponent(btn_hapus)
                            .addComponent(btn_batal)
                            .addComponent(btn_keluar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(radio_laki))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_perempuan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_admin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_kasir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_simpan)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked

    }//GEN-LAST:event_btn_simpanMouseClicked

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        int kode        = Integer.parseInt(txt_kode.getText());
        String nama     = txt_nama.getText();
        String user     = txt_user.getText();
        String password = txt_password.getText();
       
        //menentukan jenis kelamin
        String jklm = "";
        if(radio_laki.isSelected())
        {
            jklm = "laki-laki";
        }
        else if(radio_perempuan.isSelected())
        {
            jklm = "perempuan";
        }
        
        //menentukan level
        String level = "";
        if(radio_admin.isSelected())
        {
            level = "admin";
        }
        else if(radio_kasir.isSelected())
        {
            level = "kasir";
        }
        
        try
        {
            ResultSet rs = configurasi.ambildata("select * from petugas where kode_petugas = '"+kode+"'");
            if(rs.next())
            {
                txt_nama.setText(rs.getString("nama"));
                txt_user.setText(rs.getString("user"));
                txt_password.setText(rs.getString("password"));
                
                //menentukan jenis kelamin
                if(rs.getString("jklm").equals("laki-laki"))
                {
                    radio_laki.setSelected(true);
                }
                else
                {
                    radio_perempuan.setSelected(true);
                }
                
                //menentukan level
                if(rs.getString("level").equals("admin"))
                {
                    radio_admin.setSelected(true);
                }
                else
                {
                    radio_kasir.setSelected(true);
                }
                
                JOptionPane.showMessageDialog(this, "Data sudah ada");
            }
            else
            {
                configurasi.aksi("insert into petugas values('"+kode+"', '"+nama+"', '"+jklm+"', '"+user+"', '"+password+"', '"+level+"')");
                bersih();
                txt_kode.requestFocus();
                bersih_tabel();
                muat_tabel();
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
            }
        }
        catch (Exception e)
        {
            
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        aksi_edit();
        
        int row = jTable1.getSelectedRow();
        txt_kode.setText(jTable1.getValueAt(row, 0).toString());
        txt_nama.setText(jTable1.getValueAt(row, 1).toString());
        txt_user.setText(jTable1.getValueAt(row, 3).toString());
        txt_password.setText(jTable1.getValueAt(row, 4).toString());
        
        //menentukan jenis kelamin
        if(jTable1.getValueAt(row, 2).toString().equals("laki-laki"))    
        {
            radio_laki.setSelected(true);
        }
        else if(jTable1.getValueAt(row, 2).toString().equals("perempuan"))
        {
            radio_perempuan.setSelected(true);
        }
        
        //menentukan level petugas
        if(jTable1.getValueAt(row, 5).toString().equals("admin"))
        {
            radio_admin.setSelected(true);
        }
        else if(jTable1.getValueAt(row, 5).toString().equals("kasir"))
        {
            radio_kasir.setSelected(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_ubahMouseClicked

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        int kode        = Integer.parseInt(txt_kode.getText());
        String nama     = txt_nama.getText();
        String user     = txt_user.getText();
        String password = txt_password.getText();
       
        //menentukan jenis kelamin
        String jklm = "";
        if(radio_laki.isSelected())
        {
            jklm = "laki-laki";
        }
        else if(radio_perempuan.isSelected())
        {
            jklm = "perempuan";
        }
        
        //menentukan level
        String level = "";
        if(radio_admin.isSelected())
        {
            level = "admin";
        }
        else if(radio_kasir.isSelected())
        {
            level = "kasir";
        }
        
        try
        {
            configurasi.aksi("update petugas set nama = '"+nama+"', jklm = '"+jklm+"', user = '"+user+"', password = '"+password+"', level = '"+level+"' where kode_petugas = '"+kode+"'");
            bersih();
            bersih_tabel();
            muat_tabel();
            aksi_simpan();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");
        }
        catch (Exception e)
        {
            
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void txt_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodeActionPerformed

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:  
        int a = JOptionPane.showConfirmDialog(this, "Anda yakin akan menghapus barang ?", "Hapus Barang" , JOptionPane.YES_NO_OPTION);
        if(a == JOptionPane.YES_OPTION)
        {
            String kode = txt_kode.getText();
            configurasi.aksi("delete from petugas where kode_petugas = '"+kode+"'");
        
            bersih_tabel();
            muat_tabel();
            bersih();
            aksi_simpan();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_batalMouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        aksi_simpan();
        bersih();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void radio_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_adminActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmKaryawan().setVisible(true);
            }
        });
    }
    
    public void atur_tabel()
    {
        model.addColumn("kode");
        model.addColumn("nama");
        model.addColumn("jenis kelamin");
        model.addColumn("user");
        model.addColumn("password");
        model.addColumn("level");
        
        jTable1.setModel(model);
    }
    
    public void aksi_simpan()
    {
        btn_simpan.setEnabled(true);
        txt_kode.setEditable(true);
        
        btn_hapus.setEnabled(false);
        btn_ubah.setEnabled(false);
        btn_batal.setEnabled(false);
        jTable1.clearSelection();
    }
    
    public void aksi_edit()
    {
        btn_simpan.setEnabled(false);
        txt_kode.setEditable(false);
        
        btn_hapus.setEnabled(true);
        btn_ubah.setEnabled(true);
        btn_batal.setEnabled(true);
    }
    
    public void bersih()
    {
        txt_kode.setText("");
        txt_nama.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        txt_user.setText("");
        txt_password.setText("");
    }
    
    public void muat_tabel()
    {
        try
        {
            ResultSet rs = configurasi.ambildata("select * from petugas");
            while(rs.next())
            {
                model.addRow(new Object[] {
                    rs.getString("kode_petugas"),
                    rs.getString("nama"),
                    rs.getString("jklm"),
                    rs.getString("user"),
                    rs.getString("password"),
                    rs.getString("level")
                });
            }
        }
        catch (Exception e)
        {
            
        }
    }
    
    public void bersih_tabel()
    {
        int row = jTable1.getRowCount();
        for(int i = 1; i <= row; i++)
        {
            model.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radio_admin;
    private javax.swing.JRadioButton radio_kasir;
    private javax.swing.JRadioButton radio_laki;
    private javax.swing.JRadioButton radio_perempuan;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
